version: '3'
services:
  nginx:
    container_name: contrfinder_nginx
    build: ./docker/nginx
    ports:
      - 80:80
    volumes:
      - ./contrfinder-serverside:/app
      - ./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    container_name: contrfinder_app
    build: ./
    # environment:
    #   APP_ENV: 'local'
    #   APP_DEBUG: 'true'
    #   LOG_CHANNEL: 'stderr'
    #   DB_CONNECTION: 'pgsql'
    #   DB_HOST: 'db'
    #   DB_PORT: '5432'
    #   DB_DATABASE: 'contrfinder_dev'
    #   DB_USERNAME: 'postgres'
    #   DB_PASSWORD: 'postgres'
    volumes:
      - ./contrfinder-serverside:/app
    expose:
      - 9000
    depends_on:
      - db
      - testdb
    working_dir: /app

  db:
    image: postgres:10.6
    container_name: contrfinder_db
    environment:
      TZ: 'Asia/Tokyo'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'contrfinder_dev'
    ports:
      - 15432:5432

  testdb:
    image: postgres:10.6
    container_name: contrfinder_test_db
    environment:
      TZ: 'Asia/Tokyo'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'contrfinder_test_dev'
    ports:
      - 15433:5432

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - elastic
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    networks:
      - elastic

  mail:
    image: mailhog/mailhog
    container_name: "contrfinder_mail"
    ports:
      - "8065:8025"

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: bridge