version: '3'
services:
  nginx:
    container_name: contrfinder_nginx
    build: ./docker/nginx
    ports:
      - 80:80
    volumes:
      - ./contrfinder-serverside:/app
      - ./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    container_name: contrfinder_app
    build: ./
    environment:
      APP_ENV: 'local'
      APP_DEBUG: 'true'
      LOG_CHANNEL: 'stderr'
      DB_CONNECTION: 'pgsql'
      DB_HOST: 'db'
      DB_PORT: '5432'
      DB_DATABASE: 'contrfinder_dev'
      DB_USERNAME: 'postgres'
      DB_PASSWORD: 'postgres'
    volumes:
      - ./contrfinder-serverside:/app
    expose:
      - 9000
    depends_on:
      - db
    working_dir: /app

  db:
    image: postgres:10.6
    container_name: contrfinder_db
    environment:
      TZ: 'Asia/Tokyo'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'contrfinder_dev'
    ports:
      - 15432:5432

  elasticsearch:
    image: elasticsearch:5.6
    ports:
      - "9200:9200"

  mail:
    image: mailhog/mailhog
    container_name: "contrfinder_mail"
    ports:
      - "8065:8025"